/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#b4c5ff",
        "tertiary-container": "#0555dd",
        "secondary-fixed-dim": "#ddb8ff",
        "surface": "#fcf8ff",
        "on-surface-variant": "#464555",
        "primary-fixed": "#e2dfff",
        "on-error-container": "#93000a",
        "on-primary-container": "#dad7ff",
        "surface-container-high": "#eae6f4",
        "primary-fixed-dim": "#c3c0ff",
        "surface-container-low": "#f5f2ff",
        "surface-bright": "#fcf8ff",
        "on-tertiary-fixed": "#00174b",
        "tertiary": "#003fac",
        "on-background": "#1b1b24",
        "secondary": "#831ada",
        "on-primary-fixed": "#0f0069",
        "on-surface": "#1b1b24",
        "inverse-on-surface": "#f3effc",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#003ea8",
        "outline": "#777587",
        "on-tertiary-container": "#d1daff",
        "on-primary-fixed-variant": "#3323cc",
        "on-error": "#ffffff",
        "background": "#fcf8ff",
        "surface-variant": "#e4e1ee",
        "on-secondary-fixed-variant": "#6800b4",
        "error": "#ba1a1a",
        "surface-container-highest": "#e4e1ee",
        "secondary-fixed": "#f0dbff",
        "primary-container": "#4f46e5",
        "tertiary-fixed": "#dbe1ff",
        "inverse-surface": "#302f39",
        "outline-variant": "#c7c4d8",
        "primary": "#3525cd",
        "secondary-container": "#9e41f5",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-tint": "#4d44e3",
        "on-secondary-fixed": "#2c0051",
        "on-secondary-container": "#fffbff",
        "surface-container": "#f0ecf9",
        "on-primary": "#ffffff",
        "inverse-primary": "#c3c0ff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dcd8e5"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "unit": "4px",
        "container-max": "1280px",
        "md": "16px",
        "sm": "8px",
        "xl": "40px",
        "lg": "24px",
        "xs": "4px"
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "title-md": ["Inter"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "title-md": ["18px", { "lineHeight": "24px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
